---
- hosts: all
  become: yes
  tasks:
  -  name: Install epel on RedHat Family
     yum:
        name=epel-release
        state=latest
     when:
        ansible_os_family == "RedHat"
  -  name: Install zabbix on RedHat Family
     yum:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "RedHat"
     notify:
        zabbix-agent systemd
  -  name: Install zabbix on Ubuntu
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd
  -  name: copy zabbix config
     copy:
       src: /etc/ansible/zabbix/zabbix_agentd.conf
       dest: /etc/zabbix/zabbix_agentd.conf
       mode: 0644
  -  name: replase hostname
     lineinfile:
       dest: /etc/zabbix/zabbix_agentd.conf
       regexp: '^Hostname='
       line: 'Hostname={{ ansible_hostname }} '
       backrefs: yes
  handlers:
  -  name: zabbix-agent systemd
     systemd:
       name: zabbix-agent.service
       enabled: yes
       state: started
